src/main/java/ru/jblab/xmlconfig/model/KindOfSport.java
package ru.jblab.xmlconfig.model;

import ru.jblab.xmlconfig.model.enums.KindOfSportEnum;

import javax.persistence.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by Arcoo on 08.10.2014.
 */
@Entity
public class KindOfSport {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "date")
    private Long date;
    @Column(name = "name")
    private String name;
    @Column(name = "time")
    private Double time;
    @Column(name = "metric")
    private String metric;
    @Enumerated(EnumType.STRING)
    private KindOfSportEnum sportsKindEnum;

    private String value;

    public String getValue() {
        return sportsKindEnum.getValue();
    }

    public KindOfSportEnum getSportsKindEnum() {
        return sportsKindEnum;
    }

    public void setSportsKindEnum(KindOfSportEnum sportsKindEnum) {
        this.sportsKindEnum = sportsKindEnum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getTime() {
        return time;
    }

    public void setTime(Double time) {
        this.time = time;
    }

    public String getMetric() {
        return metric;
    }

    public void setMetric(String metric) {
        this.metric = metric;
    }

    public String getDateStr() {
        return new SimpleDateFormat("yyyy-MM-dd").format(new Date(date)); // or .getTime()
    }

}

src/main/java/ru/jblab/xmlconfig/controller/SportResultsController.java
package ru.jblab.xmlconfig.controller;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import ru.jblab.xmlconfig.controller.validator.KindOfSportValidator;
import ru.jblab.xmlconfig.form.KindOfSportForm;
import ru.jblab.xmlconfig.model.KindOfSport;
import ru.jblab.xmlconfig.model.enums.KindOfSportEnum;
import ru.jblab.xmlconfig.service.ISportResultService;
import ru.jblab.xmlconfig.utils.FormMapper;

import java.io.UnsupportedEncodingException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 * Created by Arcoo on 07.10.2014.aa
 */

@Controller
public class SportResultsController {

    @Autowired
    @Qualifier("WithDBSportRes")
    ISportResultService sportResService;

    @Autowired
    private KindOfSportValidator validator;

    @RequestMapping(value = "/sportResults/sportRes", method = RequestMethod.GET)
    public String renderSportResPage(ModelMap map) {
        map.addAttribute("kindOfSport", new KindOfSportForm());
        //map.addAttribute("listOfSports", sportResService.getKindsList());       // !!!!!!!!!!!
//        Map<String, List<Event>> mapEvent = timeTableEventService.getAllEvents();
//        map.addAttribute("events", mapEvent);
//        map.addAttribute("eventEnum", TimeTableEnum.getAll());
//        map.addAttribute("mapSportResults", service.getAllSportResults());
        map.addAttribute("sportKindsEnumList", KindOfSportEnum.values());   //returns List of enums;
//        map.addAttribute("defaultSportKindsEnum", KindOfSportEnum.getDefault());
        return "sportResults/sportRes";
    }

    @RequestMapping(value = "/sportResults/addSportRes", method = RequestMethod.POST)
    public String addKindOfsport(@ModelAttribute("kindOfSport") KindOfSportForm kindOfSportForm,
                                 BindingResult bindingResult, ModelMap map) throws ParseException {
        validator.validate(kindOfSportForm, bindingResult);
        if (bindingResult.hasErrors()) {
            return "sportResults/sportRes";
        } else {
            sportResService.addSportRes(kindOfSportForm);
            return "redirect:/sportResults/sportResDiary";
        }
    }

    @RequestMapping(value = "/sportResults/edit/{id}", method = RequestMethod.GET)
    public String editKindOfSport(@PathVariable("id") Long id, ModelMap map) {
        map.addAttribute("kindOfSportToEdit", FormMapper.kindOfSportToKindOfSportForm(sportResService.searchKindOfSportById(id)));
        map.addAttribute("sportKindsEnumList", KindOfSportEnum.values());
        return "/sportResults/editSportRes";
    }

    @RequestMapping(value = "/sportResults/editSportRes/{id}", method = RequestMethod.POST)
    public String updateKindOfSport(@ModelAttribute("kindOfSportToEdit") KindOfSportForm kindOfSportForm,
                                    @PathVariable("id") Long id, BindingResult bindingResult,
                                    ModelMap map) throws ParseException {
        validator.validate(kindOfSportForm, bindingResult);
        if (bindingResult.hasErrors()) {
            return "/sportResults/editSportRes";
        } else {
            kindOfSportForm.setId(id);
            sportResService.editSportRes(kindOfSportForm);      // replaces old element to new edited element in the List;
            return "redirect:/sportResults/sportResDiary";     //"redirect:/sportResults/sportRes";
        }
    }

    @RequestMapping(value = "/sportResults/delete/{id}", method = RequestMethod.GET)
    public String deleteKindOfSport(@PathVariable("id") Long id, ModelMap map) {
        sportResService.deleteKindOfSport(id);             // deletes an object, which was founded by it's attribute;
        return "redirect:/sportResults/sportRes";          // and pushes changed List<KindOfSports> into session;
    }

    @RequestMapping(value = "/sportResults/clearSportRes", method = RequestMethod.GET)
    public String clearListOfSportResults() {
        sportResService.clearListOfSportResults();
        return "redirect:/sportResults/sportRes";
    }

    @RequestMapping(value = "/sportResults/clearSportResAjax", method = RequestMethod.POST)
    public String clearListOfSportResultsAjax(@RequestParam("date") String date, ModelMap map) throws ParseException {

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Long dateLong = sdf.parse(date).getTime();
        sportResService.deleteSpecificListByDate(dateLong);
        List<KindOfSport> specificListOfSports = sportResService.findSportResultsByDate(dateLong);
        map.addAttribute("specificListOfSports", specificListOfSports);

        return "/sportResults/addSpecSportResListInclude";  //redirect:/
    }

    @RequestMapping(value = "/sportResults/sportResDiary", method = RequestMethod.GET)
    public String renderSportResDiaryPage() {
        return "sportResults/sportResDiary";
    }

    // for Ajax request method edit
    @RequestMapping(value = "/sportResults/editAjax", method = RequestMethod.POST)
    @ResponseBody
    public KindOfSport editKindOfSportAjax(@ModelAttribute("kindOfSportToEdit") KindOfSportForm kindOfSportForm)
            throws ParseException {
        sportResService.editSportRes(kindOfSportForm);
        KindOfSport kindOfSport = (FormMapper.kindOfSportFormToKindOfSport(kindOfSportForm));
        return kindOfSport;
    }

    // for Ajax request method add
    @RequestMapping(value = "/sportResults/addAjax", method = RequestMethod.POST)
    //@ResponseBody
    public String addKindOfSportAjax(@ModelAttribute("kindOfSport") KindOfSportForm kindOfSportForm,
                                     ModelMap map) throws ParseException {
        KindOfSport kindOfSport = sportResService.addSportRes(kindOfSportForm);
        map.addAttribute("kindOfsport", kindOfSport);
        return "/sportResults/addsportresInclude";
    }

    @RequestMapping(value = "/sportResults/findByDateAjax", method = RequestMethod.GET)
    //@ResponseBody
    public String findNote(@RequestParam("date") String date, ModelMap map)
            throws ParseException, UnsupportedEncodingException, JsonProcessingException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Long dateLong = sdf.parse(date).getTime();
        List<KindOfSport> specificListOfSports = sportResService.findSportResultsByDate(dateLong);
        map.addAttribute("specificListOfSports", specificListOfSports);

        return "/sportResults/addSpecSportResListInclude";
    }

    @RequestMapping(value = "/sportResults/deleteSportResAjax", method = RequestMethod.GET)
    public String deleteKindOfSportAjax(@RequestParam("id") Long id, ModelMap map) {
        KindOfSport kindOfSport = sportResService.searchKindOfSportById(id);
        Long dateLong = kindOfSport.getDate();
        sportResService.deleteKindOfSport(id);             // deletes an object, which was founded by it's attribute;

        List<KindOfSport> specificListOfSports = sportResService.findSportResultsByDate(dateLong);
        map.addAttribute("specificListOfSports", specificListOfSports);

        return "/sportResults/addSpecSportResListInclude";
    }


}

src/main/webapp/WEB-INF/pages/sportResults/addSpecSportResListInclude.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<%--
  Created by IntelliJ IDEA.
  User: ArthurRec
  Date: 11.11.2014
  Time: 17:12
  To change this template use File | Settings | File Templates.
--%>

<div>
    <c:if test="${empty specificListOfSports}">
        <h3>You haven't got any sport results</h3>
    </c:if>

    <c:if test="${not empty specificListOfSports}">
        <div>
            <c:forEach items="${specificListOfSports}" var="kindOfsport">

                <span style="font-size: larger; ">
                ${kindOfsport.dateStr}<br>
                <b>${kindOfsport.sportsKindEnum.value}</b><br>
                   ${kindOfsport.name}
                   ${kindOfsport.time}
                   ${kindOfsport.metric}
                </span>
                <br>

                <%--<input type="hidden" name="id" class="js-id" value='${kindOfsport.id}'/>--%>
                <%--<a href="/sportResults/delete/${kindOfsport.id}" class="addButton"> Delete </a>--%>

                <a href="/sportResults/edit/${kindOfsport.id}" class="addButton"> Edit </a>
                <button type="submit" class="js-delete_result addButton"
                        name="id" value='${kindOfsport.id}'> Delete
                </button>
                <br><br>

            </c:forEach>
        </div>
    </c:if>
    <%--<form:hidden path="secretValue" />--%>
    <%--<a href="/sportResults/clearSportRes" class="addClearButton">clearList</a>--%>
    <%--<button type="submit" id="clear_list" class="addClearButton">clearList</button><br>--%>
    <%--name="dateStr" value='${kindOfsport.dateStr}'--%>
</div>

src/main/webapp/WEB-INF/pages/sportResults/addsportresInclude.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: Arcoo
  Date: 29.10.2014
  Time: 19:49
  To change this template use File | Settings | File Templates.
--%>

<br><span style="font-size: larger; ">
    <b>${kindOfsport.sportsKindEnum.value}</b><br>
    ${kindOfsport.name}
    ${kindOfsport.time}
    ${kindOfsport.metric}
</span>
<br>
    <a href="/sportResults/edit/${kindOfsport.id}" class="addButton">Edit</a>
    <a href="/sportResults/delete/${kindOfsport.id}" class="addButton">Delete</a>

<%--<form action="/sportResults/sportRes" method="get" >--%>
<%--<input type="submit" value="Add result" class="addButton">--%>
<%--</form>--%>
<br>

src/main/webapp/WEB-INF/pages/sportResults/editSportRes.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: Arcoo
  Date: 11.10.2014
  Time: 23:47
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Edit sportResults</title>
    <link href="/resources/css/sportRes.css" rel="stylesheet">
    <script src="/resources/js/jquery.min.js"></script>
    <script src="/resources/js/sportResScript.js"></script>
</head>
<body>
<h2>Here you can edit your sport result</h2>
<form:form class="addForm" method="POST" action="/sportResults/editSportRes/${kindOfSportToEdit.id}"
           modelAttribute="kindOfSportToEdit">

    Please edit <b>${kindOfSportToEdit.name}</b> data:
    <form:input path="name" class="js-kindOfSportName" maxlength="20" placeholder="enter kind of sport"/><br>
    <form:errors class="error" path="name"/><br>

    <form:hidden path="date" class=".js-kindOfSportDate" value='${kindOfsportToEdit.dateStr}'></form:hidden>

    <form:select path="sportsKindEnum" class="js-sportsKindEnum">
        <%--<option selected value="${defaultSportKindsEnum.value}"></option>--%>
        <c:forEach items="${sportKindsEnumList}" var="sportsKind">
            <form:option value="${sportsKind}">${sportsKind.value}</form:option>
        </c:forEach>
    </form:select><br>
    <%--<form:errors class="error" path="sportsKindEnum"/><br>--%>

    <br><form:input path="time" class="js-time" maxlength="10" placeholder="enter time of exercise"/><br>
    <form:errors class="error" path="time"/><br>

    <form:select path="metric" class="js-metric">
        <form:option value="" label="Select"/>
        <form:option value="minutes" label="min"/>
        <form:option value="seconds" label="sec"/>
        <form:option value="hour(s)" label="hour(s)"/>
        <form:option value="kilometres" label="km"/>
        <form:option value="metres" label="metres"/>
        <form:option value="repeats" label="repeats"/>
    </form:select><br>
    <form:errors class="error" path="metric"/><br>

    <input type="submit" value="Edit" class="addButton"/>
    <input type="hidden" name="id" class="js-id" value='${kindOfSportToEdit.id}'>

    <%--<button type="submit" id="edit_btn" class="addButton"> Edit </button>--%>
    <a href="javascript:history.back()" title="Back" class="addButton"> Back </a>
</form:form>
</body>
</html>

src/main/webapp/WEB-INF/pages/sportResults/sportRes.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>My sport results</title>
    <link href="/resources/css/sportRes.css" rel="stylesheet">
    <script src="/resources/js/jquery.min.js"></script>
    <script src="/resources/js/sportResScript.js"></script>
</head>

<body>
<form:form class="addForm" action="/sportResults/addSportRes" method="post" modelAttribute="kindOfSport">
    <form:input path="name" class="js-kindOfSportName"  maxlength="20" placeholder="enter kind of sport"/><br>
    <form:errors class="error" path="name"/><br>

    <form:input type="date" path="date" class=".js-kindOfSportDate" placeholder="enter date of exercise"/><br>
    <%--<form:errors class="error" path="date"/><br>--%><br>

    <form:select path="sportsKindEnum" class="js-sportsKindEnum">
        <%--<option selected value="${defaultSportKindsEnum.value}">sportsKind</option>--%>
        <c:forEach items="${sportKindsEnumList}" var="sportsKind">
            <form:option value="${sportsKind}">${sportsKind.value}</form:option>
        </c:forEach>
    </form:select><br>

    <br><form:input path="time" class="js-time" maxlength="10" placeholder="enter time of exercise"/><br>
    <form:errors class="error" path="time"/><br>

    <form:select path="metric" class="js-metric">
        <form:option value="" label="Select"/>
        <form:option value="minutes" label="min"/>
        <form:option value="seconds" label="sec"/>
        <form:option value="hour(s)" label="hour(s)"/>
        <form:option value="kilometres" label="km"/>
        <form:option value="metres" label="metres"/>
        <form:option value="repeats" label="repeats"/>
    </form:select>

    <%--<button type="submit" id="add_btn" class="addButton">Add value JS</button><br>--%>
    <input type="submit" value="Add" class="addButton"/><br>
    <form:errors class="error" path="metric"/><br>

    <a href="javascript:history.back()" title="Back" class="addButton"> Back </a>
    <a href="/" title="HomePage" class="addButton"> HomePage </a><br>
</form:form>

<%--<div>
    <c:if test="${empty listOfSports}">
        <h3>You haven't got any sport results</h3>

        <div id="addSportResJspInclude"/>

    </c:if>
<c:if test="${not empty listOfSports}">
    <form:form cssClass="addForm">
        <c:forEach items="${listOfSports}" var="kindOfsport">

            <div id="addSportResJspInclude">
                <%--<c:set var="kindOfsport" value="${kindOfsport}" scope="request"/>
                <jsp:include page="addsportresInclude.jsp"/>
            </div>

        </c:forEach><br>
        <a href="/sportResults/clearSportRes" class="addClearButton">clearList</a>
    </form:form>
</c:if>
</div>--%>

<div class="addForm">
    <a href="/sportResults/sportResDiary" class="addButton"> SportRes diary </a>
    <a href="/" title="HomePage" class="addButton"> HomePage </a>
</div>

</body>
</html>

src/main/webapp/WEB-INF/pages/sportResults/sportResDiary.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%--
  Created by IntelliJ IDEA.
  User: ArthurRec = Arcoo
  Date: 11.11.2014
  Time: 15:35
  To change this template use File | Settings | File Templates.
--%>

<html>
<head>
    <title>SportRes diary</title>
    <link href="/resources/css/sportRes.css" rel="stylesheet">
    <link href="/resources/css/sportResInline.css" rel="stylesheet">
    <link type="text/css" href="/resources/css/jquery-ui.min.css" rel="stylesheet"/>
    <script src="/resources/js/jquery.min.js"></script>
    <script src="/resources/js/jquery-ui.min.js"></script>
    <script src="/resources/js/sportResScript.js"></script>
    <meta http-equiv="Content-Type" Content="text/html; charset=UTF-8">
</head>

<body>
<h2 align='center'> Sport results diary </h2>

<div id="datepicker"></div>
<br>

<div id="addSpecSportResListInclude" class="addForm">
    <%--<c:if test="${empty listOfSports}">
      <h3>You haven't got any sport results</h3>

      <div id="addSportResJspInclude"/>

    </c:if>
    <c:if test="${not empty listOfSports}">
      <div cssClass="addForm">
        <c:forEach items="${listOfSports}" var="kindOfsport">

          <div id="addSportResJspInclude">
              <%--<c:set var="kindOfsport" value="${kindOfsport}" scope="request"/>
            <jsp:include page="addsportresInclude.jsp"/>
          </div>

        </c:forEach><br>
        <a href="/sportResults/clearSportRes" class="addClearButton">clearList</a>
      </div>
    </c:if>--%>
    <jsp:include page="addSpecSportResListInclude.jsp"/>
</div>
<br>

<div class="addForm">
    <form action="/sportResults/sportRes" method="get">
        <input type="submit" value="Add result" class="addButton">
    </form>
    <button type="submit" id="clear_list" class="addClearButton"> clearList</button>
    <br>
</div>
<br>
</body>
</html>