src/main/java/ru/jblab/xmlconfig/form/TaskForm.java
package ru.jblab.xmlconfig.form;

/**
 * Created by root on 10.10.14.
 */
public class TaskForm {
    private String taskname;
    private String priority;
    private String comment;
    private String deadlineDate;
    private String deadlineTime;
    private String date;
    private String status;
    private int redacted;
    private long id;

    public TaskForm() {
    }

    public int getRedacted() {
        return redacted;
    }

    public void setRedacted(int redacted) {
        this.redacted = redacted;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTaskname() {
        return taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getDeadlineDate() {
        return deadlineDate;
    }

    public void setDeadlineDate(String deadlineDate) {
        this.deadlineDate = deadlineDate;
    }

    public String getDeadlineTime() {
        return deadlineTime;
    }

    public void setDeadlineTime(String deadlineTime) {
        this.deadlineTime = deadlineTime;
    }
}

src/main/java/ru/jblab/xmlconfig/model/Task.java
package ru.jblab.xmlconfig.model;

import ru.jblab.xmlconfig.model.enums.TaskPriorityEnum;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.text.SimpleDateFormat;
import java.util.Date;


@Entity
public class Task implements Comparable<Task> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String taskname;
    private String priority;
    private String comment;
    private Date date;
    private Date deadline;
    private int priorityIndex;
    private int redacted;

    private int status;


    public int getRedacted() {
        return redacted;
    }

    public void setRedacted(int redacted) {
        this.redacted = redacted;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Date getDeadline() {
        return deadline;
    }

    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    public Task(String taskname, String priority, String comment, Date deadline) {
        this.taskname = taskname;
        this.priority = priority;
        priorityIndex = TaskPriorityEnum.getByValue(priority).getPriorityWeight();
        this.comment = comment;
        date = new Date();
        this.deadline = deadline;
    }

    public Task() {
        date = new Date();
    }

    public String getTaskname() {
        return taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
        priorityIndex = TaskPriorityEnum.getByValue(priority).getPriorityWeight();
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getDateString() {
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss dd.MM.yyyy");
        return format.format(date);
    }

    public String getDeadlineString() {

        if (deadline != null) {
            SimpleDateFormat format = new SimpleDateFormat("HH:mm dd.MM.yyyy");
            return format.format(deadline);
        } else {
            return "";
        }
    }

    public boolean isFailed() {
        if (deadline == null) return false;
        return new Date().after(deadline);
    }

    public void setFailed(boolean failed) {
        boolean failed1 = new Date().after(deadline);
    }

    @Override
    public String toString() {
        return "Task{" +
                "taskname='" + taskname + '\'' +
                ", priority='" + priority + '\'' +
                ", comment='" + comment + '\'' +
                '}';
    }

    @Override
    public int compareTo(Task o) {
        if (this.priorityIndex == o.priorityIndex) {
            return this.date.compareTo(o.date);
        } else {
            return o.priorityIndex - this.priorityIndex;
        }
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getPriorityIndex() {
        return priorityIndex;
    }

    public void setPriorityIndex(int priorityIndex) {
        this.priorityIndex = priorityIndex;
    }
}

src/main/webapp/WEB-INF/pages/todolist/createtask.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<form:form class="add-task" action="/todo/add" method="post" modelAttribute="addform">
    <h1> Добавить задачу </h1>
    <form:errors path="taskname" cssClass="error"/>
    <p><form:input type="text" path="taskname" class="js-taskname"></form:input>
        <form:select path="priority" class="js-priority">
            <option selected value="${defaultTaskPriority.value}">Приоритет</option>
            <c:forEach var="taskPriority" items="${taskPriorities}">
                <form:option value="${taskPriority}">${taskPriority.value}</form:option>
            </c:forEach>
        </form:select></p>
    <p><form:errors path="deadlineDate" cssClass="error"/></p>
    Deadline:
    <form:input type="date" path="deadlineDate" class="js-deadlinedate"/>
    <form:input type="time" path="deadlineTime" class="js-deadlinetime"/>
    <form:input type="hidden" path="status" value="1" class="js-status"/>
    <form:input type="hidden" path="redacted" value="0" class="js-redacted"/>
    <p>
        <form:textarea path="comment" cols="45" rows="5" class="js-comment"></form:textarea></p>
    <button id="create-task-btn" class="button">Добавить</button>
    <input type="reset" value="Очистить" class="button">

</form:form>

src/main/webapp/WEB-INF/pages/todolist/edittask.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>


<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Редактирование задачи</title>
    <style>
        <%@include file="/WEB-INF/resources/css/todostyle.css" %>
    </style>
</head>
<body>

<form:form class="add-task" action="/todo/update/${taskToEdit.id}" method="post" modelAttribute="taskToEdit">
    <h1> Редактировать задачу </h1>
    <form:errors path="taskname" cssClass="error"/>
    <p><form:input type="text" path="taskname"></form:input>
        <form:select path="priority">
            <c:forEach var="taskPriority" items="${taskPriorities}">
                <form:option value="${taskPriority}">${taskPriority.value}</form:option>
            </c:forEach>
        </form:select></p>
    <p><form:errors path="deadlineDate" cssClass="error"/></p>
    Deadline:
    <form:input type="date" path="deadlineDate"/>
    <form:input type="time" path="deadlineTime"/>
    <form:input type="hidden" path="status" value="${taskToEdit.status}"/>
    <form:input type="hidden" path="redacted" value="1"/>
    <p>
        <form:textarea path="comment" cols="45" rows="5"></form:textarea></p>
    <input type="submit" value="Редактировать" class="button">
    <input type="reset" value="Сбросить" class="button">
</form:form>
<div class="bottom">
    <a href="/todo/show">Вернуться к списку задач</a>
</div>
</body>
</html>

src/main/webapp/WEB-INF/pages/todolist/task.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<div class="task" id="${result.id}">
    <label class="task-name">${result.taskname}</label><br>
    <c:if test="${not empty result.comment}">
        <p class="task-comment">${result.comment}</p>

        <p class="task-comment-off"></p>
    </c:if>
    <p>
        <c:choose>
            <c:when test="${result.redacted eq 0}">
                <label class="date">Создана: ${result.dateString}</label><br>
            </c:when>
            <c:otherwise>
                <label class="date">Изменена: ${result.dateString}</label><br>
            </c:otherwise>
        </c:choose>
        <c:if test="${not empty result.deadlineString}">
            <label class="deadline">Выполнить до: ${result.deadlineString}</label>
        </c:if>
        <c:if test="${result.failed eq true}">
            <label class="failed"> DEADLINE </label>
        </c:if>
    </p>
    <label class="priority">${result.priority}</label>

    <div class="controls">
        <c:if test="${not (param.status eq 1)}">
            <a href="/todo/changestatus/${result.id}/${param.status - 1}"><i class="fa fa-arrow-left"></i>
            </a>
        </c:if>

        <a href="/todo/remove/${result.id}"> <i class="fa fa-trash-o"></i>
        </a>

        <a href="/todo/edit/${result.id}"><i class="fa fa-pencil"></i>
        </a>

        <c:if test="${not (param.status eq 4)}">
            <a href="/todo/changestatus/${result.id}/${param.status + 1}"><i class="fa fa-arrow-right"></i>
            </a>
        </c:if>
    </div>
</div>

src/main/webapp/WEB-INF/pages/todolist/taskinclusion.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<label class="label-type">${param.text}</label>
<hr>
<c:forEach items="${todoList}" var="result">
    <c:if test="${result.status eq param.status}">
        <div class="task" id="${result.id}">
            <label class="task-name">${result.taskname}</label><br>
            <c:if test="${not empty result.comment}">
                <p class="task-comment">${result.comment}</p>

                <p class="task-comment-off"></p>
            </c:if>
            <p>
                <c:choose>
                    <c:when test="${result.redacted eq 0}">
                        <label class="date">Создана: ${result.dateString}</label><br>
                    </c:when>
                    <c:otherwise>
                        <label class="date">Изменена: ${result.dateString}</label><br>
                    </c:otherwise>
                </c:choose>
                <c:if test="${not empty result.deadlineString}">
                    <label class="deadline">Выполнить до: ${result.deadlineString}</label>
                </c:if>
                <c:if test="${result.failed eq true}">
                    <label class="failed"> DEADLINE </label>
                </c:if>
            </p>
            <label class="priority">${result.priority}</label>

            <div class="controls">
                <c:if test="${not (param.status eq 1)}">
                    <a href="/todo/changestatus/${result.id}/${param.status - 1}"><i class="fa fa-arrow-left"></i>
                    </a>
                </c:if>

                <a href="/todo/remove/${result.id}"> <i class="fa fa-trash-o"></i>
                </a>

                <a href="/todo/edit/${result.id}"><i class="fa fa-pencil"></i>
                </a>

                <c:if test="${not (param.status eq 4)}">
                    <a href="/todo/changestatus/${result.id}/${param.status + 1}"><i class="fa fa-arrow-right"></i>
                    </a>
                </c:if>
            </div>
        </div>
    </c:if>
</c:forEach>

src/main/webapp/WEB-INF/pages/todolist/tasks.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<head>
    <title>Список задач</title>

    <script src="../resources/js/jquery.min.js"></script>
    <script src="../resources/js/todoscript.js"></script>
    <link href="../resources/css/todostyle.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="tasks-area">
    <div class="tasks">
        <div id="new-task-adding"></div>
        <h1>Cписок задач: </h1>
        <div class="add-button">
            <a href="" id="add-new-task">Добавить ещё</a><br>
            <a href="/todo/clean">Удалить все</a>
        </div>

        <div class="task-row tasks-new">
            <jsp:include page="taskinclusion.jsp">
                <jsp:param name="status" value="1"/>
                <jsp:param name="text" value="Открытые: "/>
            </jsp:include>
        </div>

        <div class="task-row tasks-doing">
            <jsp:include page="taskinclusion.jsp">
                <jsp:param name="status" value="2"/>
                <jsp:param name="text" value="В обработке: "/>
            </jsp:include>
        </div>

        <div class="task-row tasks-check">
            <jsp:include page="taskinclusion.jsp">
                <jsp:param name="status" value="3"/>
                <jsp:param name="text" value="На проверке: "/>
            </jsp:include>
        </div>

        <div class="task-row tasks-done">
            <jsp:include page="taskinclusion.jsp">
                <jsp:param name="status" value="4"/>
                <jsp:param name="text" value="Закрытые: "/>
            </jsp:include>
        </div>
    </div>
</div>

</body>
</html>